name: CI Build and Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'assets/**'
  pull_request:
    branches:
      - master
    paths:
      - 'assets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          # 使用 pnpm 安装依赖
          run_install: true

      - name: Set up Node.js 20.13.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
          cache: 'pnpm'

      - name: Build project
        run: pnpm run build

      - name: Commit and push changes
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: master
          # 部署目录为 VuePress 的默认输出目录
          build_dir: .
          commit_message: 'feat: 自动构建资源依赖与发布版本'
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Create and push tag
        run: pnpm run release -- release-as patch --tag-force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tags to GitHub
        run: git push --follow-tags origin HEAD
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: pnpm publish --access public
        if: success()
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
